name: Build and Publish Image

permissions:
  packages: write

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
    - name: Get the short sha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build Image
      id: build-image
      run: echo "${{ steps.vars.outputs.sha_short }}"
