name: Build and Publish Image

permissions:
  packages: write

on:
  push:
    branches:
    - main

jobs:
  build:
    # if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
    - name: Get the short sha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.sha }})"

    - name: Build Image
      id: build-image
      run: echo "${{ steps.vars.outputs.sha_short }} ${{ github.event_name }}"
