name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  boilerplate:
    name: boilerplate
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'hello, world!'"
